name: Publish

on:
  push:
    branches:
      - main

jobs:
  build-upload:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - uses: actions/checkout@v3

      - name: Remove Git artificats
        run: |
          rm -rf .git
          rm -rf .github
          rm .gitignore

      - uses: konnected-io/aws-s3-github-action@master
        name: Copy to S3
        with:
          command: cp
          source: ./
          destination: s3://install-konnected/
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: us-east-1
          flags: --acl public-read --recursive

      - uses: chetan/invalidate-cloudfront-action@v2
        env:
          DISTRIBUTION: E2FDL2RANMI9J7
          PATHS: "/*"
          AWS_REGION: "us-east-1"
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}