name: Publish

on:
  push:
    branches:
      - main

jobs:
  build-upload:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - uses: actions/checkout@v2

      - uses: keithweaver/aws-s3-github-action@v1.0.0
        name: Copy AWS S3
        with:
          command: cp
          source: ./
          destination: s3://install-konnected/
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: us-east-1